import { z } from 'zod';
import { StoredThoughtFormSchema, ThoughtFormInputUnionSchema } from './thoughtform.js';
import { FLOAT32_MAX, LIMITS, NAMESPACE_PATTERN } from './limits.js';

export const VECTOR_DIMENSION = 384;

export type RepresentationType = 'vector' | 'markdown' | 'thoughtform';

export const RepresentationTypeSchema = z.enum(['vector', 'markdown', 'thoughtform']);

/**
 * Why an embedding is unusable, or null if it is a valid VECTOR_DIMENSION-d,
 * finite, float32-representable, non-zero vector (cosine needs a direction).
 */
export function embeddingProblem(embedding: unknown): string | null {
  if (!Array.isArray(embedding)) return 'embedding must be an array of numbers';
  if (embedding.length !== VECTOR_DIMENSION) {
    return `embedding must have ${VECTOR_DIMENSION} dimensions, got ${embedding.length}`;
  }
  let normSq = 0;
  for (let i = 0; i < embedding.length; i++) {
    const x: unknown = embedding[i];
    if (typeof x !== 'number' || !Number.isFinite(x) || Math.abs(x) > FLOAT32_MAX) {
      return `embedding[${i}] must be a finite float32 value`;
    }
    normSq += x * x;
  }
  if (!(normSq > 0)) return 'embedding must not be the zero vector';
  return null;
}

// --- Input schemas shared by the MCP tools and the service layer ---

export const NamespaceSchema = z
  .string()
  .regex(NAMESPACE_PATTERN, 'namespace must match ^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$');

export const TagSchema = z.string().min(1).max(LIMITS.tagChars);

export const TagsSchema = z.array(TagSchema).max(LIMITS.tags);

export const MarkdownSchema = z.string().max(LIMITS.markdownChars);

export const EmbeddingSchema = z
  .array(z.number())
  .length(VECTOR_DIMENSION)
  .superRefine((embedding, ctx) => {
    const problem = embeddingProblem(embedding);
    if (problem) ctx.addIssue({ code: z.ZodIssueCode.custom, message: problem });
  });

export const ThoughtFormInputSchema = ThoughtFormInputUnionSchema;

// --- Provenance: where each representation came from ---

/**
 * - `user`: written by a caller through a tool or the service.
 * - `derived`: computed by Polytician from another representation without an
 *   LLM (the embedding model, the thoughtform→markdown template, the
 *   rule-based NLP pipeline).
 * - `llm`: generated by an LLM (a conversion through the configured LLM
 *   provider, or a saved `vault_infer` answer).
 * - `import`: copied in from outside this server (AgentVault pulls, PolyVault
 *   restores), or declared so by the caller (an entry from another system's
 *   ledger, for example).
 *
 * `user` and `import` content is authored: a derived or LLM write never
 * replaces it unless the caller passes `overwrite`. A representation with no
 * recorded provenance (written before 3.0) counts as authored too.
 */
export const ProvenanceOriginSchema = z.enum(['user', 'derived', 'llm', 'import']);

export type ProvenanceOrigin = z.infer<typeof ProvenanceOriginSchema>;

export const ProvenanceSchema = z
  .object({
    origin: ProvenanceOriginSchema,
    /** For derived and LLM content: the representation it was made from. */
    derivedFrom: RepresentationTypeSchema.optional(),
    /** Embedding model, NLP pipeline or LLM provider that made it, or the model a caller declared. */
    model: z.string().min(1).max(LIMITS.provenanceChars).optional(),
    /** Who wrote it, as the caller declared. Recorded for audit; not authenticated. */
    createdBy: z.string().min(1).max(LIMITS.provenanceChars).optional(),
    /** Other concepts whose content was used (an LLM conversion's nearest neighbours). */
    sources: z.array(z.string()).optional(),
  })
  .strict();

export type Provenance = z.infer<typeof ProvenanceSchema>;

/** Provenance per representation; a representation absent from it has none recorded. */
export type ProvenanceMap = Partial<Record<RepresentationType, Provenance>>;

export const ProvenanceMapSchema = z.record(RepresentationTypeSchema, ProvenanceSchema);

/** Whether content was made by Polytician (derived or LLM) rather than authored. */
export function isMachineMade(provenance: Provenance | undefined): boolean {
  return provenance?.origin === 'derived' || provenance?.origin === 'llm';
}

/**
 * What a caller may declare about the representations a write supplies.
 * `derived` and `llm` are reserved for content Polytician makes itself.
 */
export const SourceSchema = z
  .object({
    origin: z
      .enum(['user', 'import'])
      .optional()
      .describe(
        '"user" (default) for content written by the caller, "import" for content copied from another system'
      ),
    createdBy: z
      .string()
      .min(1)
      .max(LIMITS.provenanceChars)
      .optional()
      .describe(
        'Who wrote the content (an agent, person or system); recorded as given, not authenticated'
      ),
    model: z
      .string()
      .min(1)
      .max(LIMITS.provenanceChars)
      .optional()
      .describe('Model that wrote the content, if the caller knows it'),
  })
  .strict();

export type Source = z.infer<typeof SourceSchema>;

// --- Assertion status: how far a concept can be relied on as a fact ---

/**
 * Truth status of a concept that records a claim, for example a stenographer
 * TB/UV entry: `asserted` (claimed, not verified), `verified`, `contested`,
 * `retracted`. Null for ordinary memories. Polytician stores the status the
 * caller gives; it does not check it against the ledger.
 */
export const AssertionStatusSchema = z.enum(['asserted', 'verified', 'contested', 'retracted']);

export type AssertionStatus = z.infer<typeof AssertionStatusSchema>;

/** Reference to the ledger entry a concept mirrors (an id, path#id or entry hash). */
export const LedgerRefSchema = z.string().min(1).max(LIMITS.ledgerRefChars);

export const ConceptSchema = z.object({
  id: z.string().uuid(),
  namespace: z.string().default('default'),
  version: z.number().int().positive(),
  createdAt: z.number(),
  updatedAt: z.number(),
  tags: z.array(z.string()).default([]),
  markdown: z.string().nullable(),
  thoughtform: StoredThoughtFormSchema.nullable(),
  embedding: z.array(z.number()).length(VECTOR_DIMENSION).nullable(),
  provenance: ProvenanceMapSchema.default({}),
  assertionStatus: AssertionStatusSchema.nullable(),
  ledgerRef: z.string().nullable(),
});

export type Concept = z.infer<typeof ConceptSchema>;

/**
 * A concept as a store holds it: what a backup record carries and a restore
 * writes back. Fields are checked for type, not against the caps and schemas
 * a new write must meet: a store migrated from 2.x holds content 2.x accepted
 * and 3.0 refuses on a new write (a thoughtform of any JSON shape, more or
 * longer tags, larger markdown, other ids and namespace names, a concept with
 * no representation), and a backup of it must restore it as it was.
 */
export const StoredConceptSchema = z.object({
  id: z.string(),
  namespace: z.string(),
  version: z.number().int().positive(),
  createdAt: z.number().int().nonnegative(),
  updatedAt: z.number().int().nonnegative(),
  tags: z.array(z.string()),
  markdown: z.string().nullable(),
  /** A ThoughtForm, or any JSON value 2.x stored as one; null for none. */
  thoughtform: z
    .unknown()
    .refine(v => v !== undefined, 'thoughtform must be present (null for none)'),
  /** Checked against the embedding rules when it is restored (a re-embedding import drops it). */
  embedding: z.array(z.number()).nullable(),
  provenance: ProvenanceMapSchema,
  assertionStatus: AssertionStatusSchema.nullable(),
  ledgerRef: LedgerRefSchema.nullable(),
});

export interface ConceptRepresentations {
  vector: boolean;
  markdown: boolean;
  thoughtform: boolean;
}

export interface SearchResult {
  id: string;
  namespace: string;
  /** (1 + cosine similarity) / 2, in [0, 1]; 1 is the same direction as the query. */
  score: number;
  tags: string[];
  representations: ConceptRepresentations;
  assertionStatus: AssertionStatus | null;
}
